Fix Invariant Violation: dangerouslyRenderMarkup
in some tests.

Full error message:

 Error: Invariant Violation: dangerouslyRenderMarkup(...): Cannot render
 markup in a worker thread. Make sure `window` and `document` are
 available globally before requiring React when unit testing or use
 React.renderToString for server rendering.

This happens because React does node.js vs. browser detection when it is
initially required and mocha-jsdom does not mock browser environment
for node until the tests start executing.

This commit mocks the browser env before anything else.